steps:
- name: 'maven:3-jdk-7-alpine'
  args: ['mvn', 'package', '-DskipTests']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest', '.']
images: [
  'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
  'gcr.io/$PROJECT_ID/$REPO_NAME:latest'
]